$primary_paletteKeyColor = ff0000
$secondary_paletteKeyColor = ff0000
$tertiary_paletteKeyColor = ff0000
$neutral_paletteKeyColor = ff0000
$neutral_variant_paletteKeyColor = ff0000
$background = 000000
$onBackground = ffffff
$surface = 000000
$surfaceDim = 000000
$surfaceBright = 000000
$surfaceContainerLowest = 000000
$surfaceContainerLow = 000000
$surfaceContainer = 000000
$surfaceContainerHigh = 000000
$surfaceContainerHighest = 000000
$onSurface = ffffff
$surfaceVariant = 000000
$onSurfaceVariant = ffffff
$inverseSurface = ff0000
$inverseOnSurface = 000000
$outline = 000000
$outlineVariant = 000000
$shadow = 000000
$scrim = 000000
$surfaceTint = ff0000
$primary = ff0000
$onPrimary = 000000
$primaryContainer = 000000
$onPrimaryContainer = ff0000
$inversePrimary = ff0000
$secondary = ff0000
$onSecondary = 000000
$secondaryContainer = 000000
$onSecondaryContainer = ff0000
$tertiary = ff0000
$onTertiary = 000000
$tertiaryContainer = 000000
$onTertiaryContainer = ff0000
$error = ff0000
$onError = 000000
$errorContainer = 000000
$onErrorContainer = ff0000
$primaryFixed = ff0000
$primaryFixedDim = ff0000
$onPrimaryFixed = 000000
$onPrimaryFixedVariant = 000000
$secondaryFixed = ff0000
$secondaryFixedDim = ff0000
$onSecondaryFixed = 000000
$onSecondaryFixedVariant = 000000
$tertiaryFixed = ff0000
$tertiaryFixedDim = ff0000
$onTertiaryFixed = 000000
$onTertiaryFixedVariant = 000000
$term0 = 343434
$term1 = EF0105
$term2 = 44def5
$term3 = ffdcf2
$term4 = 8aaed3
$term5 = 9ca5ef
$term6 = 94d0fa
$term7 = e8d3de
$term8 = ac9fa9
$term9 = F10105
$term10 = 89ecff
$term11 = c9fff3
$term12 = adc4d9
$term13 = b5baf8
$term14 = b6e1ff
$term15 = ffffff
$rosewater = ff0000
$flamingo = ff0000
$pink = ff0000
$mauve = ff0000
$red = ff0000
$maroon = ff0000
$peach = ff0000
$yellow = ff0000
$green = ff0000
$teal = ff0000
$sky = ff0000
$sapphire = ff0000
$blue = ff0000
$lavender = ff0000
$klink = ff0000
$klinkSelection = ff0000
$kvisited = ff0000
$kvisitedSelection = ff0000
$knegative = ff0000
$knegativeSelection = ff0000
$kneutral = ff0000
$kneutralSelection = ff0000
$kpositive = ff0000
$kpositiveSelection = ff0000
$text = ffffff
$subtext1 = ffffff
$subtext0 = ebebeb
$overlay2 = 000000
$overlay1 = 000000
$overlay0 = 000000
$surface2 = 000000
$surface1 = 000000
$surface0 = 000000
$base = 000000
$mantle = 000000
$crust = 000000
$success = ff0000
$onSuccess = 000000
$successContainer = 000000
$onSuccessContainer = ff0000
